function dsp = sample_dsproperties()
    %sample function to define the dsproperties for a data set

    %define a dsproperties struct and add the model metadata
    dsp = struct('Variables',[],'Row',[],'Dimensions',[]); 
    %define each variable to be included in the data table and any
    %information about the dimensions. dstable Row and Dimensions can
    %accept most data types but the values in each vector must be unique
    
    %struct entries are cell arrays and can be column or row vectors
    dsp.Variables = struct(...                      
        'Name',{'id','JNCC_Type','ERP2_Type','Type_id','Range','Vmhw',...
                   'Vmtl','Vmlw','Smhw','Smtl','Smlw','Amhw','Amtl','Amlw'},...
        'Description',{'Index','JNCC Type','ERP2 Type',...
                       'Type index','Tidal range',...
                       'Volume at Mean High Water',...
                       'Volume at Mean Tidel Level',...
                       'Volume at Mean Low Water',...
                       'Surface area at Mean High Water',...
                       'Surface area at Mean Tide Level',...
                       'Surface area at Mean Low Water',...
                       'Cross-sectional area at Mean High Water',...
                       'Cross-sectional area at Mean Tide Level',...
                       'Cross-sectional area at Mean Low Water'},...
        'Unit',{'-','-','-','-','m','m^3','m^3','m^3','m^2','m^2','m^2','m^2','m^2','m^2'},...
        'Label',{'Index','Estuary type','Estuary type',...
                 'Estuary type','Range','Volume','Volume','Volume',...
                 'Surface area','Surface area','Surface area',...
                 'Cross-sectional area','Cross-sectional area','Cross-sectional area'},...
        'QCflag',repmat({'data'},1,14)); 
    dsp.Row = struct(...
        'Name',{'Location'},...
        'Description',{'Location'},...
        'Unit',{'-'},...
        'Label',{'Location'},...
        'Format',{''});        
    dsp.Dimensions = struct(...    
        'Name',{''},...
        'Description',{''},...
        'Unit',{'-'},...
        'Label',{''},...
        'Format',{''});   
end
